Parameters:
  Plotdataparams:
    Exportedfilename: newanthaplot.png
    Xvalues:
    - 0
    - 1
    - 1.5
    - 3
    - 4.5
    - 6
    Yvaluearray:
    - - 0
      - 1.2
      - 1.5
      - 3
      - 4.5
      - 6
    - - 0
      - 1.1
      - 1.6
      - 3.5
      - 5
      - 6.6
    - - 0
      - 0.9
      - 1.3
      - 3.2
      - 4.3
      - 7
