Parameters:
  MoClo_design:
    AssemblyStandard: MoClo
    Constructname: Moflo2Assemblyproduct
    Level: Level0
    PartMoClotypesinorder:
    - Pro
    - 5U + NT1
    - CDS1
    - 3U + Ter
    Partsinorder:
    - BBa_I14018
    - Rbs
    - BBa_E0020
    - Term
    Vector: pAGM1311_M
