Parameters:
  Paintmix1:
    Colour1: yellow
    Colour1vol: 10ul
    Colour2: blue
    Colour2vol: 10ul
    Numberofcopies: 8
    OutPlate: pcrplate_with_cooler
  Paintmix10:
    Colour1: yellow
    Colour1vol: 10ul
    Colour2: blue
    Colour2vol: 10ul
    Numberofcopies: 8
    OutPlate: pcrplate_with_cooler
  Paintmix11:
    Colour1: yellow
    Colour1vol: 10ul
    Colour2: blue
    Colour2vol: 10ul
    Numberofcopies: 8
    OutPlate: pcrplate_with_cooler
  Paintmix2:
    Colour1: yellow
    Colour1vol: 10ul
    Colour2: blue
    Colour2vol: 10ul
    Numberofcopies: 8
    OutPlate: pcrplate_with_cooler
  Paintmix3:
    Colour1: water
    Colour1vol: 20ul
    Colour2: water
    Colour2vol: 0ul
    Numberofcopies: 8
    OutPlate: pcrplate_with_cooler
  Paintmix4:
    Colour1: yellow
    Colour1vol: 10ul
    Colour2: blue
    Colour2vol: 10ul
    Numberofcopies: 8
    OutPlate: pcrplate_with_cooler
  Paintmix5:
    Colour1: yellow
    Colour1vol: 10ul
    Colour2: blue
    Colour2vol: 10ul
    Numberofcopies: 8
    OutPlate: pcrplate_with_cooler
  Paintmix6:
    Colour1: yellow
    Colour1vol: 10ul
    Colour2: blue
    Colour2vol: 10ul
    Numberofcopies: 8
    OutPlate: pcrplate_with_cooler
  Paintmix7:
    Colour1: yellow
    Colour1vol: 10ul
    Colour2: blue
    Colour2vol: 10ul
    Numberofcopies: 8
    OutPlate: pcrplate_with_cooler
  Paintmix8:
    Colour1: yellow
    Colour1vol: 10ul
    Colour2: blue
    Colour2vol: 10ul
    Numberofcopies: 8
    OutPlate: pcrplate_with_cooler
  Paintmix9:
    Colour1: yellow
    Colour1vol: 10ul
    Colour2: blue
    Colour2vol: 10ul
    Numberofcopies: 8
    OutPlate: pcrplate_with_cooler
